spring.datasource.url=jdbc:mariadb://inmobiliaria-db:3306/inmobiliaria
spring.datasource.username=inmobiliaria_user
spring.datasource.password={cipher}f6cc6499e0db9510aa4ca4d66f94485ca2631e719a88cf0a4c9f34e4f5d553eb991d077ac2fdc9032d822432d3a0d454
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

logging.level.org.springframework=ERROR