spring.datasource.url=jdbc:mariadb://inmobiliaria-db:3306/inmobiliaria
spring.datasource.username=inmobiliaria_user
spring.datasource.password=inmobiliaria_password
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

logging.level.org.springframework=ERROR