spring.datasource.url=jdbc:mariadb://localhost:3306/inmobiliaria
spring.datasource.username=inmobiliaria_user
spring.datasource.password=inmobiliaria_password
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.springframework=DEBUG